### ISSUE TITLE
Latest npm package contains webpack "eval"

### ISSUE THREAD

**Issue by 0x253** [postalsys/postal-mime#1]
Hi!

Your library looks really great and I would like to use it for parsing some e-mail messages in a browser app.

Unfortunatly the latest npm package contains some `eval` statements, I think because it's a development and not a production build. Also look the first lines in the `dist/postal-mime.js` file: "ATTENTION: The "eval" devtool has been used (maybe by default in mode: "development")."

Would it be possible to publish a new version using the webpack production build without any `eval` statements?

Best regards!

**Comment by andris9** [comment]
Published updated production version as v1.0.11

**Comment by 0x253** [comment]
Looks great, thank you for the fast reply!
