### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by mfleeing** [postalsys/postal-mime#11]
const { PostalMime } = require('postal-mime');
const parser = new PostalMime();
const email = await parser.parse(email);
console.log(email.subject);
console.log(email.html);

err   : 
ReferenceError: self is not defined

**Comment by lhr0909** [comment]
So the library's main entry point is set to the non-node version. There seems to be another entry point in `dist/node.js` that works in NodeJS. I was able to resolve by patching `package.json` in the library and editing the `main` to be `dist/node.js` and make the imports work.

sharing the patch I generated using `pnpm patch`:
```
diff --git a/package.json b/package.json
index 36bb398514574de9da21c8fb5325221f34a1f6f2..cf64d8d219cdf15550ac50ffcdf0d46d1fff4ee4 100644
--- a/package.json
+++ b/package.json
@@ -2,7 +2,7 @@
     "name": "postal-mime",
     "version": "1.0.16",
     "description": "Email parser for browser environments",
-    "main": "dist/postal-mime.js",
+    "main": "dist/node.js",
     "types": "postal-mime.d.ts",
     "scripts": {
         "test": "eslint",
```

**Comment by lhr0909** [comment]
> So the library's main entry point is set to the non-node version. There seems to be another entry point in `dist/node.js` that works in NodeJS. I was able to resolve by patching `package.json` in the library and editing the `main` to be `dist/node.js` and make the imports work.
> 
> sharing the patch I generated using `pnpm patch`:
> 
> ```
> diff --git a/package.json b/package.json
> index 36bb398514574de9da21c8fb5325221f34a1f6f2..cf64d8d219cdf15550ac50ffcdf0d46d1fff4ee4 100644
> --- a/package.json
> +++ b/package.json
> @@ -2,7 +2,7 @@
>      "name": "postal-mime",
>      "version": "1.0.16",
>      "description": "Email parser for browser environments",
> -    "main": "dist/postal-mime.js",
> +    "main": "dist/node.js",
>      "types": "postal-mime.d.ts",
>      "scripts": {
>          "test": "eslint",
> ```

So turns out I didn't have to do the patch, since the library provides the way to use in NodeJS [here](https://github.com/postalsys/postal-mime#nodejs)

For using in TypeScript, I set up the entry point this way, and it is working for me:

```
// postal-mime.ts

import type PostalMime from 'postal-mime';

// eslint-disable-next-line @typescript-eslint/no-var-requires
const PostalMimeClass = require('postal-mime/dist/node').postalMime.default;

export default PostalMimeClass as typeof PostalMime;
```

`cross-blob` doesn't seem to be needed if we are on NodeJS v18 or above.

**Comment by andris9** [comment]
postal-mime v2 is published as an ES module, and there is no webpack build step anymore.
