### ISSUE TITLE
Allow 'to: Address[]' to be optional?

### ISSUE THREAD

**Issue by Dima-369** [postalsys/postal-mime#18]
I found an email where the `To: ...` entry wasn't set and then my TypeScript code crashed since the type is specified as `to: Address[];`.

I think, it should be changed to `to?: Address[];` correct?

**Comment by andris9** [comment]
I don't use TypeScript myself; the entire module is native JavaScript, not TS, and someone provided the typing file, but I have no idea if it is up to date or not (probably not). If you have any suggestions, please make a PR for the typings file [here](https://github.com/postalsys/postal-mime/blob/master/postal-mime.d.ts).
