### ISSUE TITLE
ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by binarykitchen** [postalsys/postal-mime#2]
Only comes up when you import this for a React component and run this within a jest-dom test runner.

Known issue or is there a recipe for this?

**Comment by andris9** [comment]
What is the environment? TextEncoder is a built in global both in the latest versions of browsers and Node.

**Comment by binarykitchen** [comment]
Sorry, sill me. Fixed with

```
// Polyfill for encoding which isn't present globally in jsdom
import { TextEncoder } from 'util'
global.TextEncoder = global.TextEncoder || TextEncoder
```

when setting up tests.
