### ISSUE TITLE
Could not decode gb18030

### ISSUE THREAD

**Issue by taoqf** [postalsys/postal-mime#21]
Including from.name, to.name, subject, and html.

**Comment by andris9** [comment]
I can not confirm this. I tried [this test file](https://github.com/MailCore/mailcore2/blob/master/unittest/data/summary/input/1021-chinese.eml), and the result looks like the same both from an actual email client and from Postal-mime output.

<img width="693" alt="Screenshot 2023-12-19 at 10 13 36" src="https://github.com/postalsys/postal-mime/assets/132242/2a70f74d-92d9-4b65-8f27-2ae46044cd43">

Postal-mime uses [TextDecoder](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder) so make sure your platform has ICU support enabled.

**Comment by taoqf** [comment]
> [TextDecoder](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder)
It seems it's the issue with bun. I could not create a TextDecoder when using with bun
