### ISSUE TITLE
Something weird with the exports

### ISSUE THREAD

**Issue by AuspeXeu** [postalsys/postal-mime#22]
![image](https://github.com/postalsys/postal-mime/assets/2115696/262d946b-26f8-49e2-942b-376937a1729d)

![image](https://github.com/postalsys/postal-mime/assets/2115696/c0f4019c-9639-4dbc-b6a1-bc41a23e7355)

**Comment by andris9** [comment]
v2 of PostalMime is ESM-only, you have to load it as a ESM module. If you use TypeScript you need to configure it to use import instead of require for loading PostalMime.
