### ISSUE TITLE
parse bounce emails?

### ISSUE THREAD

**Issue by tttp** [postalsys/postal-mime#28]
Hi,

I'd like to be able to handle bounce emails (from a cloudflare worker), and this library seems to be the closest to it.

Is there any plan to parse emails to identify bounce emails and their type (soft or hard bounce)? I'm aware it's more heuristic than mime standard based.

if not, would you have any suggestion of another library that would work with postal-mime that would help handle bounce?

**Comment by andris9** [comment]
Postal-mime parses the email into a structure, but it does not do anything with the contents of the email. For example, it does not try to extract the email signature from HTML, etc. This also applies to checking for bounce content.

The easiest way to check for bounces is to look if there is an attachment with content-type `message/delivery-status` and then extract the bounce information from it. Unfortunately, not all mail systems (not even all large ones) use this standard format, so in the end, you would still have to fall back to heuristics, like checking if the From address is mailder-daemon or Mail Delivery Subsystem, and so on.

**Comment by tttp** [comment]
If anyone bump into this issue, this library seems to be maintained and working fine with postal-mime:

https://github.com/crisp-oss/email-bounce-parser

for a in depth analysis of the joy of parsing emails to identify bounces (as @andris9 mentioned, message/delivery is sadly one of the many many ways a mail server use to notify a bounce)

https://github.com/zedshaw/lamson/blob/master/doc/lamsonproject.org/input/blog/2009-07-09.txt
