### ISSUE TITLE
Support .msg File From Outlook

### ISSUE THREAD

**Issue by neoxzgen** [postalsys/postal-mime#44]
Hey! The email parser works great with .eml and .mbox files. 
But when I want to parse a .msg file from Outlook, I'm getting weird results. Is there any plan to support this file format?

Best Regards

**Comment by andris9** [comment]
There are no plans to support any other file format than EML. Mbox is a container of EML files, so you should first split it up into individual EML files and parse each separately. Outlook MSG file is a binary format (EML is a human-readable text format).
