### ISSUE TITLE
message/rfc822 inline attachments, aka. subMessage, does not appear to be handled correctly

### ISSUE THREAD

**Issue by colin-stubbs** [postalsys/postal-mime#45]
I have three sample messages that include message/rfc822 attachments.

In one, the disposition is "attachment", and postal-mime correctly parses this and includes it in the attachment list.

e.g this is fine,
```
Content-type: message/rfc822
Content-disposition: attachment
```

In the other two, the disposition is "inline", and postal-mime does... seemingly nothing with it. It is not in the attachment list, and does not appear to be available anywhere else.

e.g. this is not fine and the content disappears,

```
Content-Type: message/rfc822
Content-Disposition: inline
```

The code suggests this is handled in some way, e.g. from postal-mime.js,

```
                // is it inline message/rfc822
                if (node.contentType.parsed.value === 'message/rfc822' && node.contentDisposition.parsed.value !== 'attachment') {
                    const subParser = new PostalMime();
                    node.subMessage = await subParser.parse(node.content);
```

However there does not appear to be any documentation regarding how this is supposed to work.

**Comment by andris9** [comment]
Inline message/rfc822 attachments are treated as regular HTML/text nodes, so the text from it is appended to the text of the container.

**Comment by colin-stubbs** [comment]
Right... I see... some ability to control behaviour might be a good idea?

Otherwise Postal Mime...

1. Ignores and drops all headers from the rfc822 attachment
2. Appends text and html together in an unexpected way, which is not so much an issue for plain text, but definitely a problem with HTML.

e.g. given,

Outer HTML body might have: <div>blah</div>
Inner HTML body might have: <html><head><base href=3D'
wettbewerb' /></head><body><!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN"=
><HTML><HEAD><META NAME=3D"Generator" CONTENT=3D"MS Exchange Server version=
 08.01.0240.003"></html>

Postal Mime then creates an invalid blob of HTML that will look weird if something tries to use it, if it even parses and  displays at all.

<div>blah</div><html><head><base href=3D'
wettbewerb' /></head><body><!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN"=
><HTML><HEAD><META NAME=3D"Generator" CONTENT=3D"MS Exchange Server version=
 08.01.0240.003"></html>

This isn't how inline forwards work in actual mail clients, nor is it desirable when analysis of the rfc822 attachment is needed by software, e.g. analysis of the headers in it, and analysis of the original text/html and attachments independent of the outer email that the rfc822 attachment is riding on.

I get that the assumption that "inline" suggests that it's fine to append text/html etc etc directly into the outer email text/html and attachments, however it's not always what people want or expect.

**Comment by andris9** [comment]
Postal Mime follows the original guidance for parsing and rendering the so called “mime torture” email. You can find a sample copy from here https://github.com/antoviaque/mail/blob/master/test/mime/rf-mime-torture-test-1.0.mbox

There are a bunch of rules how to treat plaintext and html - for example some nodes might have only html or only plaintext content while other nodes have both, etc.

**Comment by philippviereck** [comment]
Hi, [rfc5965](https://www.rfc-editor.org/rfc/rfc5965.txt) (the standard for ARF) does not state anything about what content-disposition should be used for the third mime part but their example uses inline, which causes the headers of the original-/reported- email to be lost when using postal-mime to parse it.

@colin-stubbs simple fix does solve this.

**Comment by andris9** [comment]
The latest PostalMime version treats message/rfc822 nodes as attachments by default for delivery-status (bounce) and feedback-report (ARF) emails. For other emails, there is the option `forceRfc822Attachments` that, if set to `true`, forces PostalMime to treat all message/rfc822 nodes as attachments, even if Content-Disposition is inline.
