### ISSUE TITLE
Inline Gif's not in the attachment array

### ISSUE THREAD

**Issue by JamesDerrickHH** [postalsys/postal-mime#48]
I've been working on a sharepoint webpart in react for my organisation that fetches drive items from sharepoint with the .eml file type and then parses them using this module.
Has worked great but seems to be one thing missing and that is handling inline gifs
The html still includes the pid content id for the gif
But the attachment array has no knowledge of it, so I'm unable to restore all inline images back into the email on preview
There isn't loads to my code as far as the parsing goes so don't think I'm missing anything
```
const emailFile: IFile = await sp.web.getFileById(uniqueid);

if(filetype === 'eml') {
  const blob: Blob = await emailFile.getBlob()
  const parsedEml = await new PostalMime().parse(blob)
  console.log(parsedEml)
}
```

For my specific example. the attachment array includes 2 elements, 1 png and 1 jpg, but then I get errors in the console as the html also has 3 image src's referencing gif's that are nowhere to be found
e.g. `<img border="0" width="45" height="45" style="width:.4687in;height:.4687in" id="_x0000_i1027" src="cid:image004.gif@01D2514D.35B6CDB0">`

Any help would be greatly appreciated

**Comment by andris9** [comment]
If there is `cid:image004.gif@01D2514D.35B6CDB0` URL in HTML, then there should be an attachment with content-id `image004.gif@01D2514D.35B6CDB0`. If postal-mime does not have such an attachment in the attachments array, then check the EML file, does the attachment even exist?
