### ISSUE TITLE
Cannot find module 'postal-mime' from [PATH]

### ISSUE THREAD

**Issue by abhiaiyer91** [postalsys/postal-mime#49]
Hi, I am running some functions that use PostalMime. All is well in my NextJS serverless environment but when I run the tests via Jest I get the following error:

```
Cannot find module 'postal-mime' from '/path/to/function'
```

What would be the remedy to this?

**Comment by andris9** [comment]
This is some kind of loader issue. PostalMime is a standard ESM module.

**Comment by ValentinH** [comment]
I faced the same issue.
We had issue in the past with ESM only packages like [query-string](https://github.com/sindresorhus/query-string/blob/main/package.json) and we had to add it to the  `transformIgnorePatterns` config:
```
  transformIgnorePatterns: [
    // query-string
    // https://github.com/sindresorhus/query-string/issues/366#issuecomment-1541174696
    'node_modules/(?!(query-string)/)',
  ],
```

However, with `postal-mime` it doesn't work.
If I manually update the `package.json` to be:
```
"exports": {
    "require": "./src/postal-mime.js",
    "import": "./src/postal-mime.js",
    "types": "./postal-mime.d.ts"
},
```

or 
```
"exports": {
    "default": "./src/postal-mime.js",
    "types": "./postal-mime.d.ts"
},
```

then it works.

Not sure of the impact of doing this though 🙈
