### ISSUE TITLE
[BUG] Attachment.content IS `ArrayBuffer` rather than`Uint8Array`

### ISSUE THREAD

**Issue by repo-ooo** [postalsys/postal-mime#50]
After days of painful debugging in the Cloudflare Email Workers environment, I finally discovered that `Attachment.content` is an `ArrayBuffer` rather than `Uint8Array`, which can cause encoding issues in other js libraries because `ArrayBuffer` does not have a `.length` property.

Please correct the type declaration.

**Comment by andris9** [comment]
Fixed in https://github.com/postalsys/postal-mime/releases/tag/v2.2.6
