### ISSUE TITLE
[ERR_PACKAGE_PATH_NOT_EXPORTED]

### ISSUE THREAD

**Issue by ChristianMP** [postalsys/postal-mime#52]
I'm trying to use this with Azure Functions, and are having some issues getting it to load.

```Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Worker was unable to load entry point "dist/src/functions/parse-email.js": No "exports" main defined in /.../node_modules/postal-mime/package.json```

After a countless of searching, I'm unable to find a solution for this, as far as I can tell, the main and exports are correct for postal-mime. Do you know of something that I may have overlooked?

For reference if relevant, this is the default `tsconfig.ts`for the Azure Function V4:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "outDir": "dist",
    "rootDir": ".",
    "sourceMap": true,
    "strict": false
  }
}
```

**Comment by andris9** [comment]
PostalMime is an ESM module not commonjs. Google for information about how to load ESM modules into Azure functions (I have no idea if this is possible or not)
