### ISSUE TITLE
Attachments with "Content-Type: message/rfc822" are inline by default 

### ISSUE THREAD

**Issue by andrewheberle** [postalsys/postal-mime#53]
I have a situation where I'm parsing emails coming from Microsoft Exchange/Exchange Online through their "journaling" functionality which sends emails with some envelope information in the body as plain text and the original email unmodified as a "message/rfc822" type attachment.

The issue I have, which may be related to #45, is that the content for the extra message is added to `text` after parsing and nowhere else, however the attachment does not have a "Content-Disposition" header, so in this case I am assuming Postal Mime is treating the attachment as inline?

Here is an example:

```
<TEXT OF EMAIL CONTAINING SENDER/RECIPIENT DETAILS>

--_f1667e3a-0d2e-497d-b96b-0580489c54d6_
Content-Type: message/rfc822

<ORIGINAL UNMODIFIED EMAIL>
```

Is there any way to change this behavior beyond inserting my own "Content-Disposition" header before parsing?

I would have assumed at the very least the attachment should appear in `attachments` with `inline` set to `true`.

**Comment by andris9** [comment]
If the Content-Disposition header is not set, the handling is decided by the client (in this case, Postal-Mime), and different email clients handle this differently. Some clients use these as inline values, and some as attachments.

I added a new option to PostalMime to allow the default behavior to be changed. See the `rfc822Attachments` configuration option from the [docs here](https://github.com/postalsys/postal-mime?tab=readme-ov-file#postalmimeparse) (requires latest Postal-Mime version).

**Comment by andrewheberle** [comment]
Amazing. Thanks so much for the quick response. 

Tested and solved my issue perfectly.
