### ISSUE TITLE
Add default to exports in package.json

### ISSUE THREAD

**Issue by LeoLetourneur** [postalsys/postal-mime#55]
Hi,

as stated here : 
- https://github.com/postalsys/postal-mime/issues/49#issuecomment-2248209216
- https://github.com/postalsys/postal-mime/issues/47#issue-2303827201

I think the build configuration is missing something in the export.
When I build and then launch the app, it's working find.
But when I launch my unit test with Jest, like that 

```
import PostalMime from 'postal-mime';

jest.mock('postal-mime', () => ({
  parse: jest.fn(),
}));
```

it is throwing the below error :

```
Cannot find module 'postal-mime' from 'my/file.test.ts'

      4 |
    > 5 | jest.mock('postal-mime', () => ({
        |      ^
      6 |   parse: jest.fn(),
      7 | }));
      8 |

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver...)
```

if I put the default node in your lib package.json exports like so
```
"exports": {
        "import": "./src/postal-mime.js",
        "default": "./src/postal-mime.js",
        "types": "./postal-mime.d.ts"
},
```
**or completly remove the *exports* node**
its working.

I don't see so many **exports** in other libraries' package.json,
so it might be working only with main & types (without exports).

Am I missing something ?

An other question, why do we need to use `import PostalMime from './node_modules/postal-mime/src/postal-mime.js';` for browser instead of `import PostalMime from 'postal-mime';` (written in readme) ? I'm using the second one, and it's working.

Thanks a lot for your lib !
Léo

**Comment by andris9** [comment]
PostalMime is an ESM module and, as such, does not need to be bundled or built at all. In order for the browser to know where the PostalMime's ESM module file actually is, you would need to use the full file path for the `import`. As you probably use some kind of bundling, then the bundler sets the location instead.
