### ISSUE TITLE
Getting Error Blob is not Defined

### ISSUE THREAD

**Issue by uzair004** [postalsys/postal-mime#59]
While using following code to parse contents of an email

<img width="733" alt="Screenshot 2024-09-22 at 2 21 50 AM" src="https://github.com/user-attachments/assets/c93af8db-f682-4f17-80ab-a2c82023a109">

It throws following error
<img width="539" alt="Screenshot 2024-09-22 at 2 22 16 AM" src="https://github.com/user-attachments/assets/aacf1be5-e51c-4b6e-824e-3272fa542f84">

**Comment by andris9** [comment]
Your runtime does not support this module. Probably too old version of Nodejs.
